// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ToDoListWebAppPracticing.Models;

#nullable disable

namespace ToDoListWebAppPracticing.Migrations
{
    [DbContext(typeof(ToDoListDbContext))]
    [Migration("20251127165441_AddToDoListDB")]
    partial class AddToDoListDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ToDoListWebAppPracticing.Models.Category", b =>
                {
                    b.Property<string>("CategoryId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = "Work",
                            Name = "งาน"
                        },
                        new
                        {
                            CategoryId = "Learning",
                            Name = "เรียนรู้"
                        },
                        new
                        {
                            CategoryId = "Personal",
                            Name = "ส่วนตัว"
                        },
                        new
                        {
                            CategoryId = "Shopping",
                            Name = "ช็อปปิ้ง"
                        },
                        new
                        {
                            CategoryId = "Others",
                            Name = "อื่นๆ"
                        });
                });

            modelBuilder.Entity("ToDoListWebAppPracticing.Models.Status", b =>
                {
                    b.Property<string>("StatusId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StatusId");

                    b.ToTable("Statuses");

                    b.HasData(
                        new
                        {
                            StatusId = "Open",
                            StatusName = "เปิด"
                        },
                        new
                        {
                            StatusId = "InProgress",
                            StatusName = "กำลังดำเนินการ"
                        },
                        new
                        {
                            StatusId = "Completed",
                            StatusName = "เสร็จสิ้น"
                        },
                        new
                        {
                            StatusId = "Close",
                            StatusName = "ปิด"
                        });
                });

            modelBuilder.Entity("ToDoListWebAppPracticing.Models.ToDoListItems", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CategoryId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Duedate")
                        .HasColumnType("datetime2");

                    b.Property<string>("StatusId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("StatusId");

                    b.ToTable("ToDoLists");
                });

            modelBuilder.Entity("ToDoListWebAppPracticing.Models.ToDoListItems", b =>
                {
                    b.HasOne("ToDoListWebAppPracticing.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ToDoListWebAppPracticing.Models.Status", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Status");
                });
#pragma warning restore 612, 618
        }
    }
}
